name: HTML Validation

on:
  workflow_run:
    workflows: ["Deploy Jekyll site to S3"]
    types: [completed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site_content
          path: ./site_content
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Validate HTML
        run: |
          npm install -g html-validate
          html-validate "./site_content/**/*.html" --config .github/htmlvalidate.json
